openai:
  url: https://api.openai.com/v1
  models:
    chat: gpt-3.5-turbo-0125
    embedding: text-embedding-3-small

milvus:
  host: localhost
  port: 19530
  data:
    database: default
    collection: document_collection

spring:
  data:
    mongodb:
      uri: mongodb://user:password@localhost:27017/db?authSource=admin
      collections:
        documents: documents

logging:
  level:
    # Set to DEBUG if you want to see client logs
    org.apache.hc.client5.http: ERROR
    us.craigmiller160.ragpractice: DEBUG
    io.milvus: DEBUG